services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      SEARXNG_SECRET_KEY: ${SEARXNG_SECRET_KEY}
      BASE_URL: ${SEARXNG_BASE_URL}
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      WEBUI_URL: ${WEBUI_URL}
      ENABLE_RAG_WEB_SEARCH: true
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
      USE_OLLAMA: ${USE_OLLAMA:-false}
      USE_CUDA: ${USE_CUDA:-false}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-/ollama}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY:-Sup3r_S3cr3t_K3y}
      # DATABASE_URL: ${DATABASE_URL:-sqlite:///${DATA_DIR}/webui.db}
      ENABLE_OPENAI_API: ${ENABLE_OPENAI_API:-false}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL:-https://api.openai.com}
      NODE_OPTIONS: --max-old-space-size=4096
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1'
    restart: unless-stopped

volumes:
  open-webui: {}
