services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
    volumes:
      - ./searxng:/etc/searxng
    restart: always